server:
  port: 8080

spring:
  profiles:
    active: dev
    include: alipay


  rabbitmq:
    enable: 0
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /novel-plus
    template:
      # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      exchange: novel.exchange
    publisher-confirms: false


  elasticsearch:
    #是否开启搜索引擎，1：开启，0：不开启
    enable: 0
    jest:
      uris: http://127.0.0.1:9200

redisson:
  singleServerConfig:
    address: 127.0.0.1:6379

jwt:
  secret: novel!#20191230
  expiration: 604800

#缓存管理密码
cache:
  manager:
    password: novel@2020117


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接 （多个用逗号分隔）
  urlPatterns: /book/addBookComment,/user/addFeedBack,/author/addBook,/author/addBookContent,/author/register.html



