#网站配置
website:
  name: 小说精品屋
  domain: xiongxyang.gitee.io/home
  keyword: ${application.website.name},小说,小说CMS,原创文学系统,开源小说系统,免费小说建站程序
  description: ${application.website.name}是一个多端（PC、WAP）阅读、功能完善的原创文学CMS系统，由前台门户系统、作家后台管理系统、平台后台管理系统、爬虫管理系统等多个子系统构成，支持会员充值、订阅模式、新闻发布和实时统计报表等功能，新书自动入库，老书自动更新。
  qq: 1179705413
